FROM public.ecr.aws/lambda/python:3.11

# Install development dependencies
RUN pip install --upgrade pip
RUN pip install awslambdaric boto3

# Copy requirements
COPY requirements.txt ${LAMBDA_TASK_ROOT}/
RUN pip install -r ${LAMBDA_TASK_ROOT}/requirements.txt

# Copy function code
COPY . ${LAMBDA_TASK_ROOT}/

# Set the CMD to your handler
CMD [ "handler.lambda_handler" ]
