import { PatientProfile, MedicalRecord, ClinicalSummary, TimelineEvent } from './types';

export const mockPatientProfile: PatientProfile = {
  id: 'patient-001',
  abhaId: '12-3456-7890-1234',
  name: 'Rajesh Kumar',
  age: 45,
  dateOfBirth: '1979-03-15',
  gender: 'male',
  photoUrl: '/mock-patient-photo.jpg',
  verified: true,
  bloodType: 'O+',
  allergies: ['Penicillin', 'Peanuts'],
  chronicConditions: ['Type 2 Diabetes', 'Hypertension'],
  emergencyContacts: [
    {
      name: 'Priya Kumar',
      relationship: 'Spouse',
      phone: '+91-98765-43210',
    },
  ],
  authorizedDoctors: [
    {
      id: 'doctor-001',
      name: 'Dr. Anjali Sharma',
      specialization: 'Endocrinology',
      hospital: 'Apollo Hospital',
      photoUrl: '/mock-doctor-1.jpg',
    },
    {
      id: 'doctor-002',
      name: 'Dr. Vikram Patel',
      specialization: 'Cardiology',
      hospital: 'Fortis Hospital',
      photoUrl: '/mock-doctor-2.jpg',
    },
  ],
  createdAt: '2023-01-15T10:00:00Z',
  updatedAt: '2024-01-20T15:30:00Z',
};

export const mockMedicalRecords: MedicalRecord[] = [
  {
    id: 'record-001',
    patientId: 'patient-001',
    title: 'Diabetes Follow-up Prescription',
    category: 'prescription',
    date: '2024-01-15',
    thumbnailUrl: '/sample-prescription.jpg',
    verified: true,
    processed: true,
    uploadedAt: '2024-01-15T09:00:00Z',
    processedAt: '2024-01-15T09:05:00Z',
  },
  {
    id: 'record-002',
    patientId: 'patient-001',
    title: 'HbA1c Test Results',
    category: 'lab-report',
    date: '2024-01-10',
    thumbnailUrl: '/mock-lab-report.jpg',
    verified: true,
    processed: true,
    uploadedAt: '2024-01-10T14:00:00Z',
    processedAt: '2024-01-10T14:03:00Z',
  },
  {
    id: 'record-003',
    patientId: 'patient-001',
    title: 'Chest X-Ray',
    category: 'scan',
    date: '2024-01-05',
    thumbnailUrl: '/mock-xray.jpg',
    verified: true,
    processed: true,
    uploadedAt: '2024-01-05T11:00:00Z',
    processedAt: '2024-01-05T11:10:00Z',
  },
  {
    id: 'record-004',
    patientId: 'patient-001',
    title: 'Blood Pressure Medication',
    category: 'prescription',
    date: '2023-12-20',
    thumbnailUrl: '/sample-prescription-2.jpg',
    verified: true,
    processed: true,
    uploadedAt: '2023-12-20T10:00:00Z',
    processedAt: '2023-12-20T10:05:00Z',
  },
];

export const mockClinicalSummary: ClinicalSummary = {
  patientId: 'patient-001',
  generatedAt: '2024-01-20T10:00:00Z',
  chiefComplaint: 'Routine diabetes follow-up, reports feeling fatigued',
  recentContext:
    'Patient has been managing Type 2 Diabetes for 5 years. Recent HbA1c shows slight elevation to 7.2%. Blood pressure controlled on current medication.',
  criticalFlags: ['HbA1c elevated', 'Fatigue reported'],
  vitals: [
    {
      type: 'blood-pressure',
      value: '128/82',
      unit: 'mmHg',
      timestamp: '2024-01-20T09:45:00Z',
      normal: true,
    },
    {
      type: 'heart-rate',
      value: '72',
      unit: 'bpm',
      timestamp: '2024-01-20T09:45:00Z',
      normal: true,
    },
    {
      type: 'temperature',
      value: '98.6',
      unit: '°F',
      timestamp: '2024-01-20T09:45:00Z',
      normal: true,
    },
    {
      type: 'oxygen-saturation',
      value: '98',
      unit: '%',
      timestamp: '2024-01-20T09:45:00Z',
      normal: true,
    },
  ],
  medications: [
    {
      name: 'Metformin',
      dosage: '500mg',
      frequency: 'Twice daily',
      startDate: '2019-03-01',
      active: true,
    },
    {
      name: 'Amlodipine',
      dosage: '5mg',
      frequency: 'Once daily',
      startDate: '2020-06-15',
      active: true,
    },
  ],
  recentLabs: [
    {
      testName: 'HbA1c',
      value: '7.2',
      unit: '%',
      referenceRange: '4.0-5.6%',
      date: '2024-01-10',
    },
  ],
  timeSavedMinutes: 15,
  confidence: 0.92,
};

export const mockTimelineEvents: TimelineEvent[] = [
  {
    id: 'event-001',
    patientId: 'patient-001',
    type: 'visit',
    date: '2024-01-15',
    title: 'Endocrinology Consultation',
    description: 'Routine diabetes follow-up with Dr. Anjali Sharma',
    icon: 'medical_services',
    structuredData: {
      doctor: 'Dr. Anjali Sharma',
      duration: '30 minutes',
      notes: 'Patient reports good compliance with medication',
    },
    doctorId: 'doctor-001',
    createdAt: '2024-01-15T10:00:00Z',
  },
  {
    id: 'event-002',
    patientId: 'patient-001',
    type: 'lab',
    date: '2024-01-10',
    title: 'HbA1c Test',
    description: 'Glycated hemoglobin test for diabetes monitoring',
    icon: 'science',
    structuredData: {
      testName: 'HbA1c',
      value: '7.2',
      unit: '%',
      referenceRange: '4.0-5.6%',
    },
    recordId: 'record-002',
    createdAt: '2024-01-10T14:00:00Z',
  },
  {
    id: 'event-003',
    patientId: 'patient-001',
    type: 'scan',
    date: '2024-01-05',
    title: 'Chest X-Ray',
    description: 'Routine chest imaging',
    icon: 'radiology',
    recordId: 'record-003',
    createdAt: '2024-01-05T11:00:00Z',
  },
  {
    id: 'event-004',
    patientId: 'patient-001',
    type: 'prescription',
    date: '2023-12-20',
    title: 'Blood Pressure Medication Refill',
    description: 'Amlodipine 5mg prescription renewed',
    icon: 'medication',
    recordId: 'record-004',
    createdAt: '2023-12-20T10:00:00Z',
  },
];

export const mockTrendData = [
  { date: '2023-10-01', value: 6.8 },
  { date: '2023-11-01', value: 6.9 },
  { date: '2023-12-01', value: 7.0 },
  { date: '2024-01-01', value: 7.2 },
];
